### ISSUE TITLE
Delete Server Messages

### ISSUE THREAD

**Issue by totalschaden** [SnakePin/Discord-Message-Deleter#1]
deleted

**Comment by snake-4** [comment]
Sorry for absence of documention, you can delete messages from a server by getting the server's ID (right click -> copy ID) then pasting it in channel ID(s) box with G added as prefix like this "Gsomerandomnumbers" and if you select Nuke GUILD(s) then click Nuke, it will delete all your messages from all servers, there is Nuke DM(s) option too :)

**Comment by totalschaden** [comment]
Wanted to say thank you for the replay, the post was intended for another git project and I somehow ended up here, when I realised it I removed the post. After your post I compiled it and it is even better and faster then the one I was checking out before. amazing 👍 Thanks alot
