### ISSUE TITLE
Server & DM Id Issue

### ISSUE THREAD

**Issue by totalschaden** [SnakePin/Discord-Message-Deleter#2]
Adding Server or DM IDs cause an error, Channel Ids work fine.

https://i.imgur.com/gkwXo5n.png

**Comment by snake-4** [comment]
Can you try to reproduce the error with the latest commit? It should provide more useful information about this exception.

**Comment by totalschaden** [comment]
https://i.imgur.com/W2ewMJQ.png

**Comment by totalschaden** [comment]
Uhm found the Issue, it was me :) Didnt put G or U infront. Just saw it in Help
