### ISSUE TITLE
Token Format changed ?

### ISSUE THREAD

**Issue by totalschaden** [SnakePin/Discord-Message-Deleter#3]
Taking Token from Ctrl+Shift+i (Discord APP) dosnt work anymore, seems the format changed ?

**Comment by snake-4** [comment]
The token format appears to be the same but apparently the Discord app no longer allows the DevTools to be opened.
I'll try to add a way to automatically get the token without using the DevTools.
Until then you can use the Discord web in your browser instead for getting the token value.

**Comment by totalschaden** [comment]
I tried to get the Token from Browser, it just wont start Deleting for some reason.
You can change C:\Users\XXXXX\AppData\Roaming\discord\settings.json to make DevTools work again.

Adding "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true

Like:
{
  "BACKGROUND_COLOR": "#202225",
  "IS_MAXIMIZED": false,
  "IS_MINIMIZED": false,
  "WINDOW_BOUNDS": {
    "x": 458,
    "y": 99,
    "width": 700,
    "height": 700
  },
  "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true
}

**Comment by snake-4** [comment]
Can you try this in your browser's console with your token, a message ID and a channel ID?
```js
let messageID = "MESSAGE_ID_HERE";
let channelID = "CHANNEL_ID_HERE";
let authID = "INSERT_TOKEN_HERE";

fetch("https://discord.com/api/v9/channels/"+channelID+"/messages/"+messageID, {
  "headers": {
    "authorization": authID
  },
  "body": null,
  "method": "DELETE",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by snake-4** [comment]
Also you can try this build that's based on the latest commit
[Dev-build.zip](https://github.com/SnakePin/Discord-Message-Deleter/files/9161183/Dev-build.zip)

**Comment by totalschaden** [comment]
> Also you can try this build that's based on the latest commit [Dev-build.zip](https://github.com/SnakePin/Discord-Message-Deleter/files/9161183/Dev-build.zip)

It works using the build linked. Sorry for the long delay and thanks for the update.
