### ISSUE TITLE
Hey, would you mind enabling Issues on your fork of `open-serial-port-monitor`?

### ISSUE THREAD

**Issue by DeflateAwning** [SnakePin/Discord-Message-Deleter#7]
https://github.com/snake-4/open-serial-port-monitor

It looks like your fork is the best one to date. Would you mind enabling issues on it? 

Sorry to contact you like this (on another repo); wasn't sure how else to do it. I'll delete this issue shortly.

**Comment by snake-4** [comment]
Done. Feel free to report any issues there.
